1.Answer

In [1]:
notlar = [85, 92, 76, 92, 100, 76, 85, 92]

# Tekrar edenleri silip benzersiz liste
benzersiz = list(set(notlar))
'''
benzersiz = []
for n in notlar:
    if n not in benzersiz:
        benzersiz.append(n)
'''
# En yüksek ve en düşük not
en_yuksek = max(notlar)
en_dusuk = min(notlar)

# Küçükten büyüğe sıralama
sirali = sorted(notlar)

print("Benzersiz:", benzersiz)
print("En yüksek:", en_yuksek)
print("En düşük:", en_dusuk)
print("Sıralı:", sirali)

Benzersiz: [100, 92, 85, 76]
En yüksek: 100
En düşük: 76
Sıralı: [76, 76, 85, 85, 92, 92, 92, 100]


2.Answer

In [2]:
def armstrong_check(sayi):
    toplam = 0
    for h in str(sayi):
        toplam += int(h) ** 3
    return toplam == sayi
'''
toplam = sum(int(h)**3 for h in str(sayi))
    return toplam == sayi
'''
print(armstrong_check(153))  # True
print(armstrong_check(250))  # False


True
False


3.Answer

In [3]:
A = {"Python", "R", "SQL", "Java"}
B = {"C++", "Python", "JavaScript", "SQL"}

print("Ortak:", A & B)
print("Sadece A:", A - B)
print("Birleşim:", sorted(A | B))


Ortak: {'SQL', 'Python'}
Sadece A: {'Java', 'R'}
Birleşim: ['C++', 'Java', 'JavaScript', 'Python', 'R', 'SQL']


4.Answer

In [9]:
import random, statistics

sayilar = [random.randint(1,100) for _ in range(10)]

ortalama = statistics.mean(sayilar)
sapma = statistics.stdev(sayilar)

print("Sayilar:", sayilar)
print("Ortalama:", ortalama)
print("Standart Sapma:", sapma)


Sayilar: [92, 25, 24, 85, 84, 32, 66, 14, 96, 36]
Ortalama: 55.4
Standart Sapma: 32.21869712518563


5.Answer

In [14]:
def kelime_sayaci(metin):
    kelimeler = metin.split()
    toplam = len(kelimeler)
    en_uzun = max(kelimeler, key=len)
    en_cok = max(set(kelimeler), key=kelimeler.count)
    return toplam, en_uzun, en_cok

print(kelime_sayaci("Techcareer ekibine teşekkür ederim . Sağladığınız eğitimler sayesinde hem teknik bilgilerimi "
                    "geliştirme hem de sektörel bakış açısı kazanma fırsatı buldum. Özellikle düzenlediğiniz dersle"
                    "r, kariyerime yön vermemde ve yeni beceriler edinmemde çok faydalı oldu. Böyle değerli içerikler su"
                    "nduğunuz için minnettarım. teşekkür , teşekkür"))


(42, 'düzenlediğiniz', 'teşekkür')


6.Answer

In [15]:
sayilar = [10, 12, 7, 36, 24, 9, 4]

ciftler = list(filter(lambda x: x%2==0, sayilar))
kareler = list(map(lambda x: x**2, ciftler))
sirali = sorted(kareler, reverse=True)

print("Çiftler:", ciftler)
print("Kareler:", kareler)
print("Azalan:", sirali)

Çiftler: [10, 12, 36, 24, 4]
Kareler: [100, 144, 1296, 576, 16]
Azalan: [1296, 576, 144, 100, 16]


7.Answer

In [16]:
kelimeler = ["veri", "bilim", "analiz", "yapayzeka", "python"]

sirali = sorted(kelimeler, key=lambda x: len(x))
print(sirali)


['veri', 'bilim', 'analiz', 'python', 'yapayzeka']


8.Answer

In [17]:
def rakam_toplami(metin):
    sayilar = [int(c) for c in metin if c.isdigit()]
    return sum(sayilar)

print(rakam_toplami("abc12def35"))  # 1+2+3+5 = 11


11


9.Answer

In [1]:
import numpy as np

array = np.random.randint(0, 51, 10)
print("Dizi:", array)
print("Ortalama:", array.mean())
print("Standart Sapma:", array.std())
print("En Büyük:", array.max())


Dizi: [ 0 33 21 14 20  6 38 16 23 42]
Ortalama: 21.3
Standart Sapma: 12.720455966670377
En Büyük: 42


10.Answer

In [2]:
matris = np.random.rand(5,5)

sutun_ort = matris.mean(axis=0)
binary = (matris > 0.5).astype(int)

print("Matris:\n", matris)
print("Sütun ortalamaları:", sutun_ort)
print("Binary matris:\n", binary)

Matris:
 [[0.34261575 0.9355643  0.86473809 0.97956011 0.25542403]
 [0.6699041  0.9061314  0.8791511  0.22955973 0.8309064 ]
 [0.08323448 0.98163269 0.67177074 0.1307483  0.37691014]
 [0.01868717 0.01755928 0.78868187 0.67567166 0.57667502]
 [0.09937856 0.41054165 0.08725219 0.10713549 0.78132634]]
Sütun ortalamaları: [0.24276401 0.65028586 0.6583188  0.42453506 0.56424839]
Binary matris:
 [[0 1 1 1 0]
 [1 1 1 0 1]
 [0 1 1 0 0]
 [0 0 1 1 1]
 [0 0 0 0 1]]
